export const equipmentList = [
  {
    id: "1",
    name: "Tractor 35HP",
    image: "/tractor-35hp.jpg",
    description: "Powerful 35HP tractor suitable for ploughing and general farm work",
    location: "Punjab",
    specs: "Power: 35 HP, Fuel: Diesel",
    dailyPrice: 800,
    weeklyPrice: 5200,
    monthlyPrice: 20000,
  },
  {
    id: "2",
    name: "Combine Harvester",
    image: "/combine-harvester.jpg",
    description: "Modern combine harvester for wheat and rice harvesting",
    location: "Haryana",
    specs: "Grain capacity: 2500L, Engine: 120HP",
    dailyPrice: 2500,
    weeklyPrice: 16000,
    monthlyPrice: 60000,
  },
  {
    id: "3",
    name: "Crop Cutting Machine",
    image: "/crop-cutting-machine.jpg",
    description: "Efficient crop cutting machine for paddy and wheat",
    location: "Uttar Pradesh",
    specs: "Width: 2.5m, Capacity: 150kg/min",
    dailyPrice: 600,
    weeklyPrice: 3800,
    monthlyPrice: 14000,
  },
  {
    id: "4",
    name: "Sprayer 200L",
    image: "/sprayer-200l.jpg",
    description: "Mounted sprayer for pesticide and fertilizer application",
    location: "Rajasthan",
    specs: "Tank: 200L, Boom: 12m",
    dailyPrice: 400,
    weeklyPrice: 2400,
    monthlyPrice: 8000,
  },
  {
    id: "5",
    name: "Thresher",
    image: "/thresher.jpg",
    description: "High-capacity thresher for grain separation",
    location: "Punjab",
    specs: "Capacity: 1500kg/hr, Power: 7.5HP",
    dailyPrice: 500,
    weeklyPrice: 3200,
    monthlyPrice: 12000,
  },
  {
    id: "6",
    name: "Seed Drill",
    image: "/seed-drill.jpg",
    description: "Precision seed drill for uniform planting",
    location: "Madhya Pradesh",
    specs: "Width: 2.5m, Seed box: 40L",
    dailyPrice: 350,
    weeklyPrice: 2100,
    monthlyPrice: 7500,
  },
  {
    id: "7",
    name: "Rotavator",
    image: "/rotavator.jpg",
    description: "Tiller for soil preparation and mixing",
    location: "Gujarat",
    specs: "Width: 2m, Tilling depth: 20cm",
    dailyPrice: 450,
    weeklyPrice: 2800,
    monthlyPrice: 10000,
  },
  {
    id: "8",
    name: "Plough",
    image: "/plough.jpg",
    description: "Traditional plough for deep soil preparation",
    location: "Karnataka",
    specs: "Furrow width: 25cm, Depth: 25cm",
    dailyPrice: 300,
    weeklyPrice: 1800,
    monthlyPrice: 6500,
  },
  {
    id: "9",
    name: "Power Tiller",
    image: "/power-tiller.jpg",
    description: "Small power tiller for small and medium farms",
    location: "Maharashtra",
    specs: "Power: 8HP, Width: 1.2m",
    dailyPrice: 400,
    weeklyPrice: 2400,
    monthlyPrice: 8500,
  },
  {
    id: "10",
    name: "Irrigation Pump",
    image: "/irrigation-pump.jpg",
    description: "Submersible pump for field irrigation",
    location: "Tamil Nadu",
    specs: "Discharge: 2000 LPH, Depth: 50m",
    dailyPrice: 350,
    weeklyPrice: 2100,
    monthlyPrice: 7500,
  },
]

export const labourList = [
  {
    id: "1",
    name: "Rajesh Kumar",
    skill: "Tractor Operator",
    experience: 8,
    location: "Punjab",
    dailyCharge: 450,
    availability: "Available",
    gender: "male",
    image: "/worker-male-1.jpg",
  },
  {
    id: "2",
    name: "Priya Singh",
    skill: "General Farm Labour",
    experience: 5,
    location: "Haryana",
    dailyCharge: 400,
    availability: "Available",
    gender: "female",
    image: "/worker-female-1.jpg",
  },
  {
    id: "3",
    name: "Amit Patel",
    skill: "Harvester Operator",
    experience: 10,
    location: "Gujarat",
    dailyCharge: 500,
    availability: "Booked",
    gender: "male",
    image: "/worker-male-2.jpg",
  },
  {
    id: "4",
    name: "Sunita Devi",
    skill: "Irrigation Helper",
    experience: 6,
    location: "Uttar Pradesh",
    dailyCharge: 380,
    availability: "Available",
    gender: "female",
    image: "/worker-female-2.jpg",
  },
  {
    id: "5",
    name: "Mohit Singh",
    skill: "Pesticide Applicator",
    experience: 7,
    location: "Rajasthan",
    dailyCharge: 420,
    availability: "Available",
    gender: "male",
    image: "/worker-male-3.jpg",
  },
  {
    id: "6",
    name: "Kavita Sharma",
    skill: "Crop Monitor",
    experience: 4,
    location: "Himachal Pradesh",
    dailyCharge: 390,
    availability: "Available",
    gender: "female",
    image: "/worker-female-3.jpg",
  },
  {
    id: "7",
    name: "Vikram Reddy",
    skill: "Soil Preparation",
    experience: 9,
    location: "Telangana",
    dailyCharge: 460,
    availability: "Available",
    gender: "male",
    image: "/worker-male-4.jpg",
  },
  {
    id: "8",
    name: "Asha Kumari",
    skill: "Seed Treatment",
    experience: 5,
    location: "Bihar",
    dailyCharge: 400,
    availability: "Booked",
    gender: "female",
    image: "/worker-female-4.jpg",
  },
  {
    id: "9",
    name: "Rohan Kumar",
    skill: "Equipment Maintenance",
    experience: 11,
    location: "Punjab",
    dailyCharge: 480,
    availability: "Available",
    gender: "male",
    image: "/worker-male-5.jpg",
  },
  {
    id: "10",
    name: "Meera Singh",
    skill: "Harvesting",
    experience: 6,
    location: "Madhya Pradesh",
    dailyCharge: 410,
    availability: "Available",
    gender: "female",
    image: "/worker-female-5.jpg",
  },
]

export const blogPosts = [
  {
    id: "1",
    title: "Advanced Soil Testing Technology Coming Soon",
    date: "2025-11-20",
    author: "AGRO RENT Team",
    excerpt: "Discover how AI-powered soil testing will revolutionize farm management in 2025",
    content:
      "Our research team is developing advanced soil testing technology that uses AI and IoT sensors to provide real-time soil health analytics. This innovation will help farmers optimize crop yields and reduce input costs by 30-40%. Stay tuned for the launch in Q1 2025.",
  },
  {
    id: "2",
    title: "Next Generation Drip Irrigation Systems",
    date: "2025-11-15",
    author: "AGRO RENT Team",
    excerpt: "Smart irrigation solutions that save water and improve crop productivity",
    content:
      "We are excited to announce our partnership with leading irrigation manufacturers to bring smart drip irrigation systems to Indian farmers. These systems use soil moisture sensors and weather data to optimize water usage. Expected launch: January 2025.",
  },
  {
    id: "3",
    title: "Precision Agriculture Drones Released",
    date: "2025-11-10",
    author: "AGRO RENT Team",
    excerpt: "Agricultural drones for crop monitoring and pest management",
    content:
      "Our latest addition to the equipment fleet - agricultural drones equipped with multispectral cameras for crop health monitoring. These drones can cover 50 hectares per day and provide detailed crop analysis reports. Available for rent starting December 2025.",
  },
  {
    id: "4",
    title: "Organic Farming Equipment Collection Expanded",
    date: "2025-11-05",
    author: "AGRO RENT Team",
    excerpt: "New range of equipment for sustainable and organic farming",
    content:
      "We have added 100+ new pieces of equipment specifically designed for organic farming practices. From vermicompost spreaders to biochar applicators, our collection now supports sustainable agriculture. Visit our platform to explore the complete range.",
  },
]
